workflows:
  android-espresso-tests:
    name: Android Espresso Tests
    instance_type: mac_mini_m2 # Or another suitable instance type
    max_build_duration: 60 # Maximum build duration in minutes

    environment:
      android_signing:
        - debugKey
        - testKeystores
      # Define any environment variables needed for your tests, e.g., API keys
      #vars:
      # EXAMPLE_API_KEY: Encrypted(...) # If using sensitive data

    triggering:
      # Define how builds are triggered, e.g., on push to a specific branch
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Start emulator
        script: |
        # Start the Android emulator with API level 34 (Android 14)
         flutter emulators --launch emulator-34
        # Wait for the emulator to be fully ready before running tests
         flutter emulators --launch emulator-34
        # Wait for the emulator to be fully ready (add a sleep command here if needed)
         sleep 60

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Generate debug keystore
        script: |
          if [ ! -f "$HOME/.android/debug.keystore" ]; then
            mkdir -p $HOME/.android
            keytool -genkeypair -v \
            -keystore $HOME/.android/debug.keystore \
            -alias androiddebugkey \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000
          else
           echo "Debug keystore already exists, skipping generation."
          fi
      - name: Run Espresso Tests
        script: |
          # This command executes your instrumented tests.
          # Ensure your test runner is configured in your build.gradle.
          ./gradlew connectedAndroidTest --warning-mode=all


    artifacts:
      # Define any artifacts to be collected, e.g., test reports
      - $CM_BUILD_DIR/android/app/build/reports/**/*.xml
      - $CM_BUILD_DIR/android/app/build/outputs/apk/androidTest/**/*.apk


    publishing:
      email:
        recipients:
          - laurence.de.villers.prog@gmail.com
        notify:
          success: true
          failure: false
